version: "3"

services:
  postgres:
    container_name: postgresdb
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    container_name: backend
    restart: on-failure
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/var/app
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    container_name: frontend
    restart: on-failure
    build:
      context: ./frontend
      args:
        API_HOST: ${API_HOST}
    ports:
      - "80:80"
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
    depends_on:
      - backend
    environment:
      WAIT_HOSTS: backend:5000
