version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:11-alpine
    volumes:
      - ./db:/var/lib/postgresql
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=importteamname_kiva
      - POSTGRES_USER=importteamname_dbadmin
      - POSTGRES_PASSWORD=ivJEZ4L4ZLNSsJ6