# Generated by Django 2.2.11 on 2020-03-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('permanent_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('main_pic_id', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('member_since', models.DateTimeField(blank=True, null=True)),
                ('personal_url', models.CharField(blank=True, max_length=300, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('loan_because', models.TextField(blank=True, null=True)),
                ('other_info', models.TextField(blank=True, null=True)),
                ('loan_purchase_num', models.IntegerField()),
                ('invited_by', models.CharField(blank=True, max_length=50, null=True)),
                ('num_invited', models.IntegerField()),
            ],
            options={
                'db_table': 'lender',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('loan_name', models.CharField(max_length=200)),
                ('original_language', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_translated', models.TextField(blank=True, null=True)),
                ('funded_amount', models.FloatField(blank=True, null=True)),
                ('loan_amount', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('image_id', models.CharField(blank=True, max_length=10, null=True)),
                ('video_id', models.CharField(blank=True, max_length=10, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sector_name', models.TextField(blank=True, null=True)),
                ('loan_use', models.CharField(blank=True, max_length=500, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('country_name', models.TextField(blank=True, null=True)),
                ('town_name', models.TextField(blank=True, null=True)),
                ('currency_policy', models.CharField(blank=True, max_length=200, null=True)),
                ('currency_exchange_coverage_rate', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('partner_id', models.CharField(blank=True, max_length=10, null=True)),
                ('posted_time', models.DateTimeField(blank=True, null=True)),
                ('planned_expiration_time', models.DateTimeField(blank=True, null=True)),
                ('disburse_time', models.DateTimeField(blank=True, null=True)),
                ('raised_time', models.DateTimeField(blank=True, null=True)),
                ('lender_term', models.IntegerField(blank=True, null=True)),
                ('num_lenders_total', models.IntegerField(blank=True, null=True)),
                ('num_journal_entries', models.IntegerField(blank=True, null=True)),
                ('num_bulk_entries', models.IntegerField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('borrower_names', models.TextField(blank=True, null=True)),
                ('borrower_genders', models.TextField(blank=True, null=True)),
                ('borrower_pictured', models.TextField(blank=True, null=True)),
                ('repayment_interval', models.CharField(blank=True, max_length=50, null=True)),
                ('distribution_model', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'loan',
            },
        ),
        migrations.CreateModel(
            name='LoanLender',
            fields=[
                ('loan_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lenders', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_lender',
            },
        ),
    ]
