# Generated by Django 2.2.11 on 2020-05-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiva', '0002_auto_20200502_1659'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(check=models.Q(loan_amount__gt=0), name='loan_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(check=models.Q(funded_amount__gte=0), name='funded_amount_gte_0'),
        ),
    ]
